# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::671588136887:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VL6TKC6512ON
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::671588136887:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 8175cbb2-2121-46c7-bdc2-bd653467a97a
